sudo: required

language: c

compiler:
  - gcc
  - clang

arch:
  packages:
    - cmake
    - xorg-server-xwayland
    - asciidoc
    - json-c
    - wayland
    - xcb-util-image
    - pango
    - cairo
    - gdk-pixbuf2
    - wlc-git
    - cmocka
  script:
    - "cmake ."
    - "make"
    - "make check"

script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
