name: Check build for Fedora.

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  fedora-build:
    container: fedora:37
    runs-on: ubuntu-latest

    steps:
      - name: Install tooling for source RPM build
        run: |
          dnf -y install @development-tools @rpm-development-tools
          dnf -y install rpkg git
          dnf -y install 'dnf-command(builddep)'

      # It is necessary to checkout into sub-directory, because of some weird ownership problems cause by using containers
      - name: Check out sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: swayfx

      - name: Copy spec into root dir
        run: |
          cd swayfx
          cp ./build-scripts/swayfx.rpkg.spec ./

      - name: Generate spec
        run: |
          cd swayfx
          mkdir specs
          rpkg spec --source --outdir specs

      - name: Install build dependencies
        run: |
          cd swayfx
          dnf -y builddep ./specs/swayfx.rpkg.spec

      - name: Local build
        run: |
          cd swayfx
          mkdir -p out
          rpkg local --out `pwd`/out
